### ISSUE TITLE
Неверное количество результатов на первой странице поиска по авторам

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-API#31]
Например, `https://api.fantlab.ru/search-autors?q=martin&page=1` возвращает 6 результатов, `page=2` и далее - 201.

**Comment by Mazian** [comment]
```
total: 212,
total_found: 212,
```
вроде всё корректно отдается.
что за 6 результатов?
может это глюк был системный и временный и уже не актуалекн?

**Comment by kenrube** [comment]
Проверил - все норм, но баг действительно был долгое время :) Похоже, случайно починили

**Comment by kenrube** [comment]
Баг не исчез, описание верное, только запрос не совсем такой: `https://api.fantlab.ru/search-autors?q=мартин&page=1`

**Comment by Mazian** [comment]
нет, не подтверждаю. значения одинаковые

> https://api.fantlab.ru/search-autors?q=%D0%BC%D0%B0%D1%80%D1%82%D0%B8%D0%BD&page=1

```
total_found: 252,
```

> https://api.fantlab.ru/search-autors?q=%D0%BC%D0%B0%D1%80%D1%82%D0%B8%D0%BD&page=2
```
total_found: 252,
```

**Comment by kenrube** [comment]
Да что за чертовщина! Это какой-то плавающий баг, гарантирую. В следующий раз скрин приложу :)

**Comment by kenrube** [comment]
Вад, проблема есть
![screenshot_1542622153](https://user-images.githubusercontent.com/12854618/48700208-83c7de80-ebfc-11e8-871b-e0092c0b9515.png)
![screenshot_1542622165](https://user-images.githubusercontent.com/12854618/48700209-84607500-ebfc-11e8-8b1b-1f1a72b0555a.png)

**Comment by Mazian** [comment]
А в чем проблема то пиши.
Разные запросы - разные находилки - все логично.

**Comment by kenrube** [comment]
@Mazian Проблема в количестве результатов, как обычно :) Глянь наверху

**Comment by Mazian** [comment]
Я совершенно перестал что-либо понимать чтото. в этой явно несуществующей и надуманной проблеме то.
На скриншотах у тебя результатов 6 и 7 
А апи - 253 и 217 выдают. 
По этим же самым запросам.
Ты лучше именно на примере api-выдачь показывай проблем проблем. Для однозначности.



Написано на дощечке, пахнущей свежими яблоками.

**Comment by kenrube** [comment]
@Mazian no problem. как повторится - скину скрины апи

**Comment by kenrube** [comment]
<img width="515" alt="screenshot 2018-11-25 at 15 06 43" src="https://user-images.githubusercontent.com/12854618/48978893-11577280-f0c4-11e8-8e10-95c15c569f81.png">
<img width="512" alt="screenshot 2018-11-25 at 15 07 07" src="https://user-images.githubusercontent.com/12854618/48978898-1ddbcb00-f0c4-11e8-9ade-47590cb19c98.png">
![screencapture-fantlab-ru-search-autors-2018-11-25-15_04_40](https://user-images.githubusercontent.com/12854618/48978915-58ddfe80-f0c4-11e8-9d4a-cffbd19bbe3d.png)

**Comment by kenrube** [comment]
а вот на сайте первая страница (здесь не отображается, [ссылка](https://user-images.githubusercontent.com/12854618/48978915-58ddfe80-f0c4-11e8-9d4a-cffbd19bbe3d.png))

**Comment by Mazian** [comment]
Проблема не ушла.
Делаем что б отдавать полный список.

**Comment by kenrube** [comment]
Не повторяется, закрываю
