### ISSUE TITLE
Классификация возвращается не полностью

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-API#34]
Проще рассмотреть на примере. Произведение: ["Талисман для стюардессы" Владимира Яцкевича](http://fantlab.ru/work261359), у него довольно разветвленная классификация (я ж заполнял). Запрашиваем [через api](https://api.fantlab.ru/work/261359/extended) и в _classificatory_ видим, что в группе "Общие характеристики" возвращается только 1 результат, с сюжетными ходами то же самое.

**Comment by Mazian** [comment]
- [x] сделал рефактинг вывода классификатора (был в старом коде)
- [x] ошибку с выводом только 1 рузельтата характеристик нашел, исправил.
- [x] вывод классификатора в work обновил - добавил проценты и голоса. что бы дать общее кол-во классификаций - добавился "надуровень" в иерархию - [документацию](https://github.com/FantLab/FantLab-API/blob/master/Docs/work.md) обновил
