### ISSUE TITLE
Присылать в результатах поиска по воркам work_type_id

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-API#37]
Это облегчит жизнь андроид-клиенту - позволит не выводить пустую вкладку с вложенными ворками (по-умолчанию она добавляется, на случай цикла; да и вообще список вкладок формируется до получения результата от сервера)

**Comment by Mazian** [comment]
незачет за тикет без ссылки!

https://api.fantlab.ru/search-works.json?q=%D0%B3%D0%B8%D0%BF%D0%B5%D1%80%D0%B8%D0%BE%D0%BD
сюда насколько понимаю добавить work_type_id нужно...
