### ISSUE TITLE
iOS-клиент

### ISSUE THREAD

**Issue by geor-kasapidi** [FantLab/FantLab-API#42]
Пару недель назад наткнулся на этот репозиторий и решил что вполне могу запилить ios-апп :)

[Ссылка на реп](https://github.com/geor-kasapidi/FantLab-iOS)

На данный момент готовы: парсер текста (поддерживаются используемые сабсеты bb и html тегов, эмотиконы -> эмоджи), экран отзывов произведения и треть экрана самого произведения. Также готов весь инфрастуктурный код, что позволяет полностью сосредоточиться на бизнес логике аппа (клепать экраны).

Вот тут можно глянуть [демо-видео](https://youtu.be/2925GVvsOa8)

P.S. фантлаб сильно меня выручает и я с радостью помогу с ios-клиентом

P.P.S. проектом я занимаюсь в свободное время, и если продолжать в том же темпе, то где-то в февралю закончу MVP-версию

**Comment by kenrube** [comment]
@geor-kasapidi, прекрасное начинание :) Не хочешь перенести проект в [организацию](https://github.com/FantLab)? Какой функционал планируешь для MVP?

Если будут какие-то вопросы, смело задавай. По API - либо @Mazian, либо мне, по логике и ограничениям (в части того, что уже реализовано в [android-клиенте](https://github.com/FantLab/FantLab-client)) - @HombreTech или, опять же, мне.

**Comment by HombreTech** [comment]
Даёшь FantLab на все платформы! 😀
Поможем, чем сможем.

**Comment by geor-kasapidi** [comment]
@kenrube @HombreTech спасибо :) Я буду поглядывать в андроид-версию и в случае возникновения вопросов - обязательно напишу.

1. Перенос проекта - хорошая идея, да и вы будете активность видеть.

2. Насчет MVP - я хочу видеть в первом релизе как минимум полноценный поиск и навигацию. Плюс логин и добавление в избранное (книжные полки). Хочется еще планы издательств и поиск по жанрам - но в описании АПИ я не нашел методов (может пропустил), так что отложу это на потом.

**Comment by kenrube** [comment]
@Mazian книжные полки ;)

**Comment by kenrube** [comment]
@geor-kasapidi отправил приглашение. В настройках проекта можно его сконвертировать в проект организации

**Comment by geor-kasapidi** [comment]
@kenrube done 👍

**Comment by Mazian** [comment]
@geor-kasapidi Классное начинание! 
Я сам юзер ios - рад буду и попользоваться и потестить.
