### ISSUE TITLE
Добавить в ручку work/analogs урл на обложку

### ISSUE THREAD

**Issue by geor-kasapidi** [FantLab/FantLab-API#43]
Сейчас есть TODO на стандартизацию ответа этой ручки, но было бы также неплохо иметь в ответе урл на обложку - в интерфейсе можно будет сделать какую-нибудь красивость

**Comment by Mazian** [comment]
Добавлен формат вывода "похожих" в стандарте миникарточек:
https://github.com/FantLab/FantLab-API/blob/master/Docs/work.md#%D0%9F%D0%BE%D1%85%D0%BE%D0%B6%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F

пример:
https://api.fantlab.ru/work/1/similars
