### ISSUE TITLE
Получение отзыва по его ID?

### ISSUE THREAD

**Issue by pavlo** [FantLab/FantLab-API#44]
Хотел узнать, есть ли возможность получить (GET) отзыв по его ID? Ожидал увидеть что-то навроде `https://api.fantlab.ru/responses/366381`, но ничего подобного в документации не обнаружил.

Занимаюсь ML, строю определенную модель по отзывам пользователей. Для этого нужны отзывы и чем больше, тем лучше! Получение отзывов по пользователю или книге - далеко не самый оптимальный вариант, так для периодического получения новых отзывов прийдется проходить по ВСЕМ пользователям и проверять, были у них новые записи. Куда проще было бы запомнить ID последнего отзыва и, скажем, раз в неделю получать новые - чьи ID больше запомненного.

Надеюсь внятно описал мой случай.
Спасибо!

**Comment by kenrube** [comment]
Привет! Как вариант, можно заюзать [ленту отзывов](https://github.com/FantLab/FantLab-API/blob/master/Docs/responses.md#%D0%BD%D0%BE%D0%B2%D1%8B%D0%B5-%D0%BE%D1%82%D0%B7%D1%8B%D0%B2%D1%8B-%D0%BD%D0%B0-%D1%81%D0%B0%D0%B9%D1%82%D0%B5). В ответ там приходит и id отзывов, разумеется, на который можно ориентироваться при периодической загрузке.

**Comment by Mazian** [comment]
пока отдельного урла на отдельный response мы не планируем.  
есть списки - они покрывают все нужды. свежие отзывы идут лентой - тут все верно Кен написал
