### ISSUE TITLE
JWT вместо кук

### ISSUE THREAD

**Issue by geor-kasapidi** [FantLab/FantLab-API#48]
сабж (обсуждение в чатике по мобилкам)

**Comment by kenrube** [comment]
Немного ссылок `cookie vs jwt`:
- [JWT vs cookies for token-based authentication](https://stackoverflow.com/q/37582444)
- [Significant differences between Cookies and JWT for native mobile apps](https://stackoverflow.com/q/29200503)
- [JSON Web Tokens vs. Session Cookies: In Practice](https://ponyfoo.com/articles/json-web-tokens-vs-session-cookies)
- [Cookies vs Tokens: The Definitive Guide](http://web.archive.org/web/20170715221710/https://auth0.com/blog/cookies-vs-tokens-definitive-guide/)

**Comment by kenrube** [comment]
@Mazian какие мысли?

**Comment by kenrube** [comment]
https://github.com/FantLab/FantLab-Go/issues/178
