### ISSUE TITLE
Заменить заглушку ворк-постера

### ISSUE THREAD

**Issue by Mazian** [FantLab/FantLab-API#49]
У типов окромя романа и антологии - у этих может быть оправдано «ищем обложку»

![ed1d7c45-065d-4a1d-9c56-31b735b3e7ea](https://user-images.githubusercontent.com/5379752/52695308-3948ca80-2f7d-11e9-9638-77092f78e953.png)

**Comment by Mazian** [comment]
конфиг заглушек по типам
https://api.fantlab.ru/conf/worktypes.json

**Comment by kenrube** [comment]
fantlab.ru/img/coverwork_reportage.svg - 404

**Comment by Mazian** [comment]
спасибо. пофиксил в этом json-конфиге
верная ссылка на https://fantlab.ru/img/coverwork_article.svg

**Comment by kenrube** [comment]
https://api.fantlab.ru/conf/worktypes.json удален, на замену теперь есть https://api.fantlab.ru/config.json
