### ISSUE TITLE
Не отдавать как json на ворк для оглавлений-категорий

### ISSUE THREAD

**Issue by Mazian** [FantLab/FantLab-API#52]
речь про неактивные ворки
https://fantlab.ru/work1128

**Comment by kenrube** [comment]
Не думаю, что это баг. Страница итак доступна любому пользователю (и даже незарегистрированным), так что выводить ее содержимое или нет - решать пользователю API, а никак не нам

**Comment by parserpro** [comment]
Согласен, при условии что в JSON есть статус ворка

**Comment by kenrube** [comment]
В [вроде бы любой] выдаче ворка есть поле `work_parent`, если не `null` - значит, неактивный
