### ISSUE TITLE
Дата последнего посещения в ISO

### ISSUE THREAD

**Issue by HombreTech** [FantLab/FantLab-API#55]
Сейчас дата последнего посещения пользователя отдается без спецификации часового пояса в следующем виде:
`2019-02-21 19:06:17`
Прошу сделать согласно ISO_8601:
`2008-06-22T12:54:10+03`

Пример того, где это уже сделано (**response_date_iso**):  https://api.fantlab.ru/work/1/responses
Пример, где отдается в обычном виде (**date_of_last_action**): https://api.fantlab.ru/user/164435

**Comment by kenrube** [comment]
Везде, где есть даты в формате DateTime, добавлены дублирующие поля с постфиксом `_iso`, в которых та же дата в формате ISO 8601:
- [Autor](https://github.com/FantLab/FantLab-API/blob/master/Docs/author.md#%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0%D1%8F-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F) - `last_modified_iso`
- [Bookcase](https://github.com/FantLab/FantLab-API/blob/master/Docs/bookcases.md#%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D0%BF%D0%BE%D0%BB%D0%BE%D0%BA-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F) - `date_of_add_iso`, `date_of_edit_iso`
- Publisher (список издательств) - `date_of_add_iso`, `date_of_change_iso`
- [Pubnews](https://github.com/FantLab/FantLab-API/blob/master/Docs/pubnews.md) - `date_of_add_iso` и `popularity_date_of_calc_iso` в массиве objects планов автора (autplans), `approx_release_date_iso`, `correct_date_iso` и `popularity_date_of_calc_iso` в массиве objects новинок (pubnews) и планов (pubplans) издательств
- [User](https://github.com/FantLab/FantLab-API/blob/master/Docs/user.md#%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0%D1%8F-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F) - `birthday_iso`, `date_of_reg_iso`, `date_of_last_action_iso`, `date_of_block_iso`, `date_of_block_end_iso`
- [Work](https://github.com/FantLab/FantLab-API/blob/master/Docs/work.md#%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0%D1%8F-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F) - `last_modified_iso`
