### ISSUE TITLE
Проверить добавление произведений на книжную полку

### ISSUE THREAD

**Issue by zizafantlab** [FantLab/FantLab-API#63]
**После добавлении произведений на полку неправильно считается счётчик произведений на полке.**

Я добавил на полку произведения с work_id от 1 до 100, но так как не все номера в базе заняты, фактически добавилось 84 произведения.

Однако счетчик на странице со списком книжных полок:
https://fantlab.ru/user122312/bookcases
показывает, что на полке 100 произведений, а не 84:

>     Test12345 100 шт.
>     № | правка
> 

хотя на странице самой полки:
https://fantlab.ru/bookcase186169
их 84.

То же неправильное число произведений на полке и число страниц показывает ответ запроса содержимого полки:
https://fantlab.ru/bookcasechange186169?offset=0

>     "count":100,"current_page":null,"offset":"0","offset_h":10,"page_count":10

Страниц должно быть 9, а не 10.

**Comment by kenrube** [comment]
Насколько я помню, это связано с тем, что при записи в базу существование этих произведений (так же как и изданий, и фильмов) никак не проверяется. А при выводе отображаются только те, что реально существуют

**Comment by zizafantlab** [comment]
То есть несуществующие произведения добавляются и учитываются. На полке они есть, но не показываются.

Как-то не очень правильно. Надо бы или их не учитывать, или в документации это написать. Получается счётчик не реально отображаемых произведений, а добавленных на полку, включая несуществующие произведения.

Выбери, как проще сделать. Если документацию, я сам напишу. И потом issue закроем, чтобы не висело зря :-)

**Comment by kenrube** [comment]
Вообще, это очевидный баг. Надо подумать, как починить по-нормальному. Скорее всего, просто адаптирую решение из Go-API, в нем этой проблемы [нет](https://github.com/FantLab/FantLab-Go/blob/ddebadbba65f5b35e89818b0e1ccadfd8c465a2d/sources/apiserver/internal/endpoints/add_work_bookcase_item.go#L44-L46). Займусь, как будет время

**Comment by kenrube** [comment]
Исправил, несуществующие item-ы на полку не добавляются

**Comment by zizafantlab** [comment]
Спасибо  :1st_place_medal:
