### ISSUE TITLE
Ошибка API при поиске по ISBN

### ISSUE THREAD

**Issue by zizafantlab** [FantLab/FantLab-API#67]
Поиск по ISBN не всегда правильно работает. На коротких номерах издательств ищет нормально. А вот на длинном — нет.

Вот такой поиск:
https://api.fantlab.ru/search-editions?q=978-5-907220-31-7&onlymatches=1
возвращает издания с совсем другими значениями поля isbn1, не совпадающими с "978-5-907220-31-7":

    978-5-907220-07-2
    978-5-907220-01-0
    978-5-907220-02-7
    978-5-907220-00-3
    978-5-907220-04-1
    978-5-907220-03-4

**Comment by kenrube** [comment]
TODO: после мержа https://github.com/parserpro/fantlab/pull/1008 обновить документацию по основному поиску и поиску изданий

**Comment by kenrube** [comment]
https://github.com/parserpro/fantlab/pull/1008
