### ISSUE TITLE
В документации неправильный тип в возвращаемом значении при авторизации (auth.md)

### ISSUE THREAD

**Issue by zizafantlab** [FantLab/FantLab-API#68]
Документация по авторизации (https://github.com/FantLab/FantLab-API/blob/master/Docs/auth.md) указывает, что при неудаче возвращается:
> error_msg: Int,                    # сообщение о причине отказа в авторизации

Но оказалось, что возвращается не номер ошибки типа Int, а сообщение об ошибке типа String.

И хорошо бы перечислить в документации все выдаваемые сообщения об ошибках:
- "Авторизация с этими логином и паролем не удалась"
- "Пустое значение у логина или пароля"

Может быть, ещё какие сообщения есть, но мне не попадались.

**Comment by kenrube** [comment]
Исправлено, тексты ошибок добавлены. Кроме этих, других нет
