### ISSUE TITLE
Ошибка в запросе содержимого книжных полок (в документации bookcases.md)

### ISSUE THREAD

**Issue by zizafantlab** [FantLab/FantLab-API#69]
В bookcases.md запрос содержимого книжной полки (подборки) указан как:

> GET /user{user_id}/bookcase{bookcase_id}?offset={offset}

Пропущена косая черта:
- между _user_ и {user_id}
- между _bookcase_ и {bookcase_id}

Должно быть так:

> GET /user/{user_id}/bookcase/{bookcase_id}?offset={offset}

**Comment by kenrube** [comment]
@zizafantlab Учись создавать Pull request-ы, это полезное умение :)

**Comment by zizafantlab** [comment]
Изучаю :-)

1. Сделал fork
2. Исправил у себя bookcases.md
3. Сделал branch
4. Создал pull request

Это всё? Больше ничего не надо?

**Comment by kenrube** [comment]
Да, в целом это все, красавчик. Единственное, я еще обычно аттачу issue к PR-у: справа в оформленном PR есть пункт Linked Issues, на него можно кликнуть и привязать задачу, которая автоматом закроется при его мерже. Чтобы вручную не делать
