### ISSUE TITLE
Добавить в список авторов поле фантастов

### ISSUE THREAD

**Issue by zizafantlab** [FantLab/FantLab-API#71]
В запросе списка авторов (author.md):
`GET /autors/{X}`
у каждого автора возвращается поле фантастоведа (0 или 1):
`is_fv: Boolean,        # является ли автор фантастоведом`

Хорошо бы ещё возвращать в этом запросе у каждого автора тип фантаста (0, 1 или 2):
`fantastic: Int,                   # ?`
такой же как возвращается при запросе основной информации о конкретном авторе:
`GET /autor/{id}`

Надо для ускорения генерации списка открытых авторов-нефантастов. В той версии, что есть сейчас, в списке открытых авторов возвращается более 3500 авторов и, чтобы определить, кто из них нефантаст, приходится делать столько же запросов _GET /autor/{id}_ . Это очень долго.

**Update.**

И ещё страну надо бы добавить - поле country_name из autor. Сейчас посмотрел - в статье ещё и страна присутствует.

**Comment by kenrube** [comment]
Сделано
