### ISSUE TITLE
не выводились поля content и images_plus при обычном выводе edition

### ISSUE THREAD

**Issue by Mazian** [FantLab/FantLab-API#8]

**Comment by kenrube** [comment]
Поля выводятся в [расширенном варианте](https://github.com/FantLab/FantLab-API/blob/master/Docs/edition.md#%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F)
