### ISSUE TITLE
проблема с выводом вложенности содержания в edition

### ISSUE THREAD

**Issue by Mazian** [FantLab/FantLab-API#9]
на примере сложных содержаний:
https://api.fantlab.ru/edition/68463/extended

**Comment by Mazian** [comment]
Так, подшаманил - убрал пустые строки и сделал что бы пробелы кол-во пробелов в начале строки - соответствовали уровню вложения.
Пример тот же https://api.fantlab.ru/edition/68463/extended

Документацию [обновил](https://github.com/FantLab/FantLab-API/blob/master/Docs/edition.md#%D0%A0%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F). Удачи! =)

**Comment by kenrube** [comment]
@HombreTech можешь тоже подшаманить? :)

**Comment by HombreTech** [comment]
@kenrube Уже расчехляю костыли. 😀
